### ISSUE TITLE
Untrusted certificate

### ISSUE THREAD

**Issue by andylin2004** [stuyspec/stuyspec-rewrite#13]
![image](https://user-images.githubusercontent.com/60021592/226135307-d5eebea7-ee82-4a06-9e16-af176c260ff3.png)![image](https://user-images.githubusercontent.com/60021592/226135325-689d2fa5-29d3-45a3-bbe5-7811c6f18b51.png)

As shown above, the new Stuy Spec website seems to have a certificate issue—probably mismatched host info between the actual host and the said host. In Safari, a security issue pops up. I'm smart enough to act with caution, but maybe others aren't.

**Comment by leomet07** [comment]
Seems like an issue on the www subdomain - certificate was only generated for stuyspec.com itself. Will address.
